# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AptUtilClient' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AptUtilClient
  platform :ios, '9.0'
  pod 'Firebase/Core', '~> 5.3.0'

  target 'AptUtilClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AptUtilClient-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AptUtilClient-tvOS

  target 'AptUtilClient-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
